- hosts: localhost
  become: true
  pre_tasks:
    - name: Update pkgs
      pacman:
        update_cache: true
    - name: Upgrade
      pacman:
        upgrade: true
  tasks:
    - include: tasks/shell.yml
    - include: tasks/omf.yml
